repos:
  - repo: https://github.com/terraform-docs/terraform-docs
    rev: "v0.17.0"             # e.g. "v0.11.2"
    hooks:
      - id: terraform-docs-go
        args: ["--output-file", "README.md" ]