name: Release

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - '**/*.tf'
      - '**/*.md'
      - '.github/workflows/*.yml'
      - 'LICENSE'

permissions:
  contents: write
  pull-requests: write

jobs:
  release:
    name: Release
    runs-on: ubuntu-22.04
    # Skip running release workflow on forks
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          fetch-depth: 0
      - name: Release
        uses: cycjimmy/semantic-release-action@v4.0.0
        with:
          semantic_version: 19.0.5
          extra_plugins: |
            @semantic-release/changelog@6.0.1
            @semantic-release/git@10.0.1
            conventional-changelog-conventionalcommits@5.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Token to be able to change log to main, token Repository Permissions > Contents
          # read and write access to the repository
