name: Security Checks

on:
  pull_request

permissions:
  contents: read

jobs:
  security:
    name: Security Checks
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Checkov
      uses: bridgecrewio/checkov-action@v12
      env:
        TF_HOST_NAME: tfe.karla-gabriel.sbx.hashidemos.io
        TF_REGISTRY_TOKEN: ${{ secrets.TF_ORG_TOKEN }}
      with:
        output_format: cli
        output_file_path: console
        quiet: true
        skip_check: CKV_AWS_119,CKV_AWS_28,CKV2_AWS_61,CKV_AWS_144,CKV2_AWS_62,CKV2_AWS_16,CKV_AWS_18,CKV_TF_1,CKV_AWS_300,CKV_AWS_21,CKV2_AWS_6,CKV_AWS_145
        download_external_modules: true